### PR TITLE
removing 'z' flag for tar invocation 

### PR DESCRIPTION
**Pull request by amuegge**
z flag forces gz and overrides file type detection.  fixes https://github.com/microsoft/azure-pipelines-tool-lib/issues/69

### CODE REVIEW

**Comment by amuegge** [comment]
thanks for the mac version bump.

**Comment by amuegge** [comment]
@damccorm  - i'm hoping these check failures are similar to https://github.com/microsoft/azure-pipelines-tool-lib/pull/72 .  mind advising me on the best way to get this working?

**Comment by amuegge** [comment]
Err, now the checks pass.  Previous result was 3/3 OS targets failed with timeouts.  Current run passed with no changes.  

Aced it?

**Comment by damccorm** [comment]
I reran, it looked like the website we use for testing was having issues. This lgtm, thanks for the contribution

**Comment by amuegge** [comment]
👍

**Pull request merged**
