### PR TITLE
Add Retries to Tool Retrieval

### PR DESCRIPTION
**Pull request by magleaso**
Per [#10170](https://github.com/microsoft/azure-pipelines-tasks/issues/10170)

### CODE REVIEW

**Comment by damccorm** [comment]
I don't think this will work without consuming a more recent version of the typed-rest-client. Also, could you add tests?

**Comment by magleaso** [comment]
I've written a test to trigger a timeout, but I'm getting an odd error when it does.

Uncaught TypeError: socket.end is not a function
      at OverriddenClientRequest.req.setTimeout (node_modules\typed-rest-client\HttpClient.js:247:24)
      at Socket.emitRequestTimeout (_http_client.js:661:40)
      at Socket.applyDelay (node_modules\nock\lib\socket.js:54:12)
      at respond (node_modules\nock\lib\request_overrider.js:497:22)
      at process._tickCallback (internal/process/next_tick.js:61:11)

This refers to [code in the typed rest client](https://github.com/microsoft/typed-rest-client/blob/db388ca114dffc1e241ae81e6f3b9cd022c5b281/lib/HttpClient.ts#L339), but this looks like it should be a valid function call.

**Comment by damccorm** [comment]
Could you share your test code?

**Comment by damccorm** [comment]
Hm, I've never used nock's socketDelay, I suspect `.socketDelay(180001)` is the culprit though. What are you trying to do with that line?

**Comment by magleaso** [comment]
It simulates a delay before sending the response from the server. It works as expected. If you set it to 180000, it gets a 404. Once you go over the timeout defined in that code I linked to above, it calls socket.end and that exception throws

**Comment by damccorm** [comment]
So that's almost definitely the culprit. That goes over the socket timeout leading to a `ETIMEDOUT` exception which we don't retry on (by design). You can see the codes we retry on at https://github.com/microsoft/typed-rest-client/blob/db388ca114dffc1e241ae81e6f3b9cd022c5b281/lib/HttpClient.ts#L41

**Comment by magleaso** [comment]
When there's a timeout, there is no http code returned to the client. The client closes the socket after the timeout is reached. Changing the response code to 502 still causes the same error

**Comment by damccorm** [comment]
Yeah, that's what I mean. If we timeout the socket the client doesn't retry, it only retries if it receives one of those error codes.

We choose not to retry on socket timeouts because that probably indicates that the server can't handle the load - or at least we don't have enough info to be sure what we should do (and for that reason we don't retry on any socket errors, just Http codes). If you're getting terminated by a socket error (e.g. ECONNRESET or ETIMEDOUT) but still really want retries, we recommend catching the error and manually trying again.

Looking at the error you're actually trying to solve for, it won't be resolved by using the typed-rest-client retries, I'd recommend implementing your own retry logic if you're sure that the issue is being caused by something that you actually want to retry on.

**Comment by damccorm** [comment]
With that said, I do think its worth adding the PR you have here, your tests just need to look a little different.

**Comment by magleaso** [comment]
I expect that this test will still fail, but it should fail with [this error](https://github.com/microsoft/typed-rest-client/blob/db388ca114dffc1e241ae81e6f3b9cd022c5b281/lib/HttpClient.ts#L341). Don't you think the error message is concerning?

**Comment by damccorm** [comment]
Yeah, that error doesn't look right. Added an issue in the typed-rest-client to handle that

**Comment by magleaso** [comment]
> With that said, I do think its worth adding the PR you have here, your tests just need to look a little different.

What do you think about 'allowRetries' and 'maxRetries' in the request options? They don't do anything without updating the typed rest client, so should I do that or just remove them?

**Comment by damccorm** [comment]
Why not just upgrade to the new typed-rest-client?

**Comment by magleaso** [comment]
No particular reason. Wasn't sure what the bar is for that kind of change or whether there are risks involved. Updating the typed rest client causes existing tests to fail for some reason, so I'm looking into that

**Comment by magleaso** [comment]
Figured it out. There's an off by 1 error in the typed rest client. The client will retry n times where n = maxRetries + 1

**Comment by magleaso** [comment]
@damccorm  This is ready for review now. All in all, just updated libraries, added that test which is failing due to #159, switched over the retry logic to use the retries built into latest typed-rest-client, and a couple nits.

**Comment by damccorm** [comment]
We need to fix the test. We should be able to catch the error it is currently throwing, regardless I'm not really sure why we're testing the timeout functionality to begin with - shouldn't we be testing the retry functionality in this pr? Lets just not timeout and return a failing http code instead

**Comment by magleaso** [comment]
There's already a test for retries on failing http codes, so I'm just going to remove my test.

**Comment by damccorm** [comment]
Oh, lost track of the fact that we're already retrying on some error codes. So this change isn't really functional then, its just shelling the work out to the typed-rest-client?

**Comment by magleaso** [comment]
Yes

**Comment by damccorm** [comment]
Yeah, existing tests are probably fine then. Sorry for all the excessive back and forth here

**Comment by magleaso** [comment]
No problem

**Pull request merged**
